import os
import sys
import streamlit as st
from database.aws_db import load_alerts
import pandas as pd
import plotly.express as px
from streamlit_autorefresh import st_autorefresh


sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

st_autorefresh(
    interval=5000,
    key="refresh"
)

# Page Configuration
st.set_page_config(
    page_title="Federated AI Threat Intelligence Platform",
    page_icon="🛡️",
    layout="wide"
)

st.title("🛡️ Federated AI-based Edge Threat Intelligence Platform")
st.markdown("### Industrial IoT Security Monitoring Dashboard")
st.divider()



# Database Connection
# for AWS DynamoDB
from database.aws_db import load_alerts
try:
    df = load_alerts()
    if df.empty:
        st.warning("No alerts available.")
        st.stop()

except Exception as e:
    st.error(f"Database Error: {e}")
    st.stop()

# KPI Cards
total_alerts = len(df)
high_alerts = len(df[df["severity"] == "HIGH"])
medium_alerts = len(df[df["severity"] == "MEDIUM"])
low_alerts = len(df[df["severity"] == "LOW"])

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        label="📋 Total Alerts",
        value=total_alerts
    )

with col2:
    st.metric(
        label="🔴 High",
        value=high_alerts
    )

with col3:
    st.metric(
        label="🟠 Medium",
        value=medium_alerts
    )

with col4:
    st.metric(
        label="🟢 Low",
        value=low_alerts
    )

st.divider()

# Charts
left_col, right_col = st.columns(2)
with left_col:

    st.subheader("Threat Distribution")

    severity_counts = (
        df["severity"]
        .value_counts()
        .reset_index()
    )

    severity_counts.columns = ["Severity", "Count"]

    fig_pie = px.pie(
        severity_counts,
        names="Severity",
        values="Count",
        hole=0.4,
        title="Alerts by Severity"
    )

    fig_pie.update_layout(
        margin=dict(l=20, r=20, t=50, b=20)
    )

    st.plotly_chart(fig_pie, use_container_width=True)

with right_col:

    st.subheader("Alerts by Machine")

    machine_counts = (
        df["device_id"]
        .value_counts()
        .reset_index()
    )

    machine_counts.columns = ["Machine", "Alerts"]

    fig_bar = px.bar(
        machine_counts,
        x="Machine",
        y="Alerts",
        text="Alerts",
        title="Alerts Generated by Each Machine"
    )

    fig_bar.update_traces(textposition="outside")

    fig_bar.update_layout(
        margin=dict(l=20, r=20, t=50, b=20)
    )

    st.plotly_chart(fig_bar, use_container_width=True)

st.divider()



# Recent Alerts
st.subheader("📋 Recent Threat Alerts")

# Select only the important columns
display_df = df[[
    "timestamp",
    "device_id",
    "cpu",
    "memory",
    "temperature",
    "threat_score",
    "severity",
    "recommendation"
]].copy()

# Rename columns for better display
display_df.columns = [
    "Timestamp",
    "Machine",
    "CPU (%)",
    "Memory (%)",
    "Temperature (°C)",
    "Threat Score",
    "Severity",
    "Recommendation"
]

# Round numeric values
display_df["CPU (%)"] = display_df["CPU (%)"].round(2)
display_df["Memory (%)"] = display_df["Memory (%)"].round(2)
display_df["Temperature (°C)"] = display_df["Temperature (°C)"].round(2)

# Show latest 15 alerts
display_df = display_df.sort_values(
    by=["Severity", "Threat Score"],
    ascending=[True, False]
)

st.dataframe(
    display_df.head(15),
    use_container_width=True,
    hide_index=True,
    height=450
)

# System Status
st.subheader("🖥️ System Status")

c1, c2, c3, c4 = st.columns(4)

with c1:
    st.success("✅ MQTT Broker")

with c2:
    st.success("✅ Edge Node")

with c3:
    st.success("✅ Fog Node")

with c4:
    st.success("✅ DynamoDB")




# Sidebar
st.sidebar.title("Platform Info")
st.sidebar.markdown("---")

st.sidebar.write("**Project**")
st.sidebar.write("Federated AI-based Edge Threat Intelligence Platform")

st.sidebar.write("**Course**")
st.sidebar.write("Fog & Edge Computing")

st.sidebar.write("**AI Model**")
st.sidebar.write("Isolation Forest")

st.sidebar.write("**Database**")
st.sidebar.write("Amazon DynamoDB")

st.sidebar.write("**Cloud Target**")
st.sidebar.write("AWS IoT Core + Lambda + DynamoDB")


# Latest Alert Summary
df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

latest = df.sort_values(
    by="timestamp",
    ascending=False
).iloc[0]
st.info(
    f"""
Latest Detection

Machine: {latest['device_id']}

Severity: {latest['severity']}

Threat Score: {latest['threat_score']}

Recommendation: {latest['recommendation']}
"""
)


st.markdown("---")

st.caption(
    "Federated AI-based Edge Threat Intelligence Platform | MSc Project | 2026"
)